language: node_js
 - "7"

sudo: required
dist: trusty

before_script:
  - npm install -g gulp-cli
addons:
  apt_packages:
  - pandoc

script:
  - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-science
  - npm install
  - bash tools/travis-deploy.sh
